#!/bin/bash -ex

# grub tweaks
cur=$(grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | sed "s/.*=\"\(.*\)\"/\1/")
new=$(echo "$cur xencons=hvc0 console=hvc0" | sed "s/^ *//g")
sed -i "/GRUB_CMDLINE_LINUX_DEFAULT=/ s/=.*/=\"$new\"/" /etc/default/grub

sed -i "/GRUB_HIDDEN_TIMEOUT=/ s/=.*/=true/" /etc/default/grub
sed -i "/GRUB_TIMEOUT=/ s/=.*/=0/" /etc/default/grub

chmod -x /etc/grub.d/*
chmod +x /etc/grub.d/40_custom
update-grub
ln -sf /boot/grub/grub.cfg /boot/grub/menu.lst

# Remove UNCONFIGURED INTERFACES in interfaces file
sed '/# Unconfigured INTERFACES/d' file

# (move to eth0 LA - this came from cloud patch) uncomment eth1 in interfaces file (commented out in common - see #952)
# sed -i "/eth1/ s|^#||" /etc/network/interfaces
# (not needed as is present LA) uncomment eth0 in interfaces file (commented out in common - see #952)
# sed -i "/eth0/ s|^#||" /etc/network/interfaces

ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

# disable confconsole init script
update-rc.d -f confconsole disable

# redirect inithook output (preseeded headless deployment)
sed -i '/REDIRECT_OUTPUT/ s/=.*/=true/g' /etc/default/inithooks

